
version: "3.7"
services:
  php:
    build: 
      context: ./
    privileged: true
    volumes:
      - .:/var/www/plvote
    command: /bin/bash -c " cd /var/www/plvote && composer update &&  php -S 0.0.0.0:8080 -t /var/www/plvote/www"
    ports:
      - "8080:8080"
    networks:
      - plnet  
  redis:
    image: redis    
    ports: 
      - "6379:6379"
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=plvote
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./plvote.sql:/docker-entrypoint-initdb.d/plvote.sql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  plnet:
  pldb:
    external: true
    name: shared_mysql