
version: "2.3"
services:
  php:
    build: 
      context: ./
    privileged: true
    volumes:
      - .:/var/www/plvote
    command:  php -S 0.0.0.0:8080 -t /var/www/plvote/www
    ports:
      - "8080:8080"
  redis:
    image: redis    
    ports: 
      - "6379:6379"
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=plvote
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks: 
  default:
    driver: bridge